apiVersion: v1
kind: Namespace
metadata:
  name: es-dev
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: es-dev
  name: quickstart
spec:
  version: 8.17.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false