apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: es-dev
spec:
  version: 8.17.1
  count: 1
  elasticsearchRef:
    name: quickstart
  kibanaRef: 
    name: quickstart