apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  namespace: es-dev
  name: quickstart
spec:
  version: 8.17.1
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    xpack.fleet.packages:
    - name: apm
      version: latest